apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        name: frontend
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
